11_user:11_user.c 12_user 21_user 22_user
	gcc -o 11_user 11_user.c
12_user:12_user.c
	gcc -o 12_user 12_user.c
21_user:21_user.c
	gcc -o 21_user 21_user.c
22_user:22_user.c
	gcc -o 22_user 22_user.c
.PHONY:clean
clean:
	rm -rf 11_user 12_user 21_user 22_user
